/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AApp: typeof import('antd').App
  const AButton: typeof import('antd').Button
  const AConfigProvider: typeof import('antd').ConfigProvider
  const AWatermark: typeof import('antd').Watermark
  const Activity: typeof import('react').Activity
  const Fragment: typeof import('react').Fragment
  const IconGridiconsFullscreen: typeof import('~icons/gridicons/fullscreen.tsx').default
  const IconGridiconsFullscreenExit: typeof import('~icons/gridicons/fullscreen-exit.tsx').default
  const Suspense: typeof import('react').Suspense
  const SvgIcon: typeof import('../components/SvgIcon').default
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const destroyMessage: typeof import('../config').destroyMessage
  const destroyNotification: typeof import('../config').destroyNotification
  const forwardRef: typeof import('react').forwardRef
  const globalConfig: typeof import('../config').globalConfig
  const initAntdProvider: typeof import('../config').initAntdProvider
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const showConfirmModal: typeof import('../config').showConfirmModal
  const showErrorMessage: typeof import('../config').showErrorMessage
  const showErrorModal: typeof import('../config').showErrorModal
  const showErrorNotification: typeof import('../config').showErrorNotification
  const showInfoMessage: typeof import('../config').showInfoMessage
  const showInfoModal: typeof import('../config').showInfoModal
  const showInfoNotification: typeof import('../config').showInfoNotification
  const showLoadingMessage: typeof import('../config').showLoadingMessage
  const showMessage: typeof import('../config').showMessage
  const showModal: typeof import('../config').showModal
  const showNotification: typeof import('../config').showNotification
  const showSuccessMessage: typeof import('../config').showSuccessMessage
  const showSuccessModal: typeof import('../config').showSuccessModal
  const showSuccessNotification: typeof import('../config').showSuccessNotification
  const showWarningMessage: typeof import('../config').showWarningMessage
  const showWarningModal: typeof import('../config').showWarningModal
  const showWarningNotification: typeof import('../config').showWarningNotification
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useNow: typeof import('../hooks/use-now').useNow
  const useOptimistic: typeof import('react').useOptimistic
  const usePreferredColorScheme: typeof import('../hooks/use-preferred-color-scheme').usePreferredColorScheme
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FC } from 'react'
  import('react')
  // @ts-ignore
  export type { ThemeName } from '../hooks/use-preferred-color-scheme'
  import('../hooks/use-preferred-color-scheme')
}
