export const LAYOUT_MODE = {
  HORIZONTAL: 'horizontal',
  TOP_HYBRID_HEADER_FIRST: 'top-hybrid-header-first',
  TOP_HYBRID_SIDEBAR_FIRST: 'top-hybrid-sidebar-first',
  VERTICAL: 'vertical',
  VERTICAL_HYBRID_HEADER_FIRST: 'vertical-hybrid-header-first',
  VERTICAL_MIX: 'vertical-mix'
} as const satisfies Record<string, UnionKey.ThemeLayoutMode>;

export const LAYOUT_MODE_VERTICAL = LAYOUT_MODE.VERTICAL;

export const LAYOUT_MODE_HORIZONTAL = LAYOUT_MODE.HORIZONTAL;

export const LAYOUT_MODE_VERTICAL_MIX = LAYOUT_MODE.VERTICAL_MIX;

export const LAYOUT_MODE_VERTICAL_HYBRID_HEADER_FIRST = LAYOUT_MODE.VERTICAL_HYBRID_HEADER_FIRST;

export const LAYOUT_MODE_TOP_HYBRID_SIDEBAR_FIRST = LAYOUT_MODE.TOP_HYBRID_SIDEBAR_FIRST;

export const LAYOUT_MODE_TOP_HYBRID_HEADER_FIRST = LAYOUT_MODE.TOP_HYBRID_HEADER_FIRST;

export const VERTICAL_LAYOUT_MODES: UnionKey.ThemeLayoutMode[] = [
  LAYOUT_MODE_VERTICAL,
  LAYOUT_MODE_VERTICAL_MIX,
  LAYOUT_MODE_VERTICAL_HYBRID_HEADER_FIRST
];

export const TOP_HYBRID_LAYOUT_MODES: UnionKey.ThemeLayoutMode[] = [
  LAYOUT_MODE_TOP_HYBRID_SIDEBAR_FIRST,
  LAYOUT_MODE_TOP_HYBRID_HEADER_FIRST
];

export const HYBRID_LAYOUT_MODES: UnionKey.ThemeLayoutMode[] = [
  LAYOUT_MODE_VERTICAL_HYBRID_HEADER_FIRST,
  LAYOUT_MODE_TOP_HYBRID_SIDEBAR_FIRST,
  LAYOUT_MODE_TOP_HYBRID_HEADER_FIRST
];

export const MIX_OR_HYBRID_LAYOUT_MODES: UnionKey.ThemeLayoutMode[] = [
  LAYOUT_MODE_VERTICAL_MIX,
  ...HYBRID_LAYOUT_MODES
];

export const FIRST_LEVEL_LAYOUT_MODES: UnionKey.ThemeLayoutMode[] = [
  LAYOUT_MODE_VERTICAL_HYBRID_HEADER_FIRST,
  LAYOUT_MODE_TOP_HYBRID_SIDEBAR_FIRST,
  LAYOUT_MODE_TOP_HYBRID_HEADER_FIRST
];

export const GLOBAL_HEADER_MENU_ID = '__GLOBAL_HEADER_MENU__';

export const GLOBAL_HEADER_MENU_SELECTOR = `#${GLOBAL_HEADER_MENU_ID}`;

export const GLOBAL_SIDER_MENU_ID = '__GLOBAL_SIDER_MENU__';

export const GLOBAL_SIDER_MENU_SELECTOR = `#${GLOBAL_SIDER_MENU_ID}`;
