/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../pages/__root'
import { Route as adminLayoutRouteImport } from './../../pages/(admin)/layout'
import { Route as IndexRouteImport } from './../../pages/index'
import { Route as errors500RouteImport } from './../../pages/(errors)/500'
import { Route as errors404RouteImport } from './../../pages/(errors)/404'
import { Route as errors403RouteImport } from './../../pages/(errors)/403'
import { Route as authLoginOutRouteImport } from './../../pages/(auth)/login-out'
import { Route as adminUserCenterRouteImport } from './../../pages/(admin)/user-center'
import { Route as adminSoybeanDocsIframeRouteImport } from './../../pages/(admin)/soybean-docs-iframe'
import { Route as adminSoybeanDocsRouteImport } from './../../pages/(admin)/soybean-docs'
import { Route as adminKeepAliveFormRouteImport } from './../../pages/(admin)/keep-alive-form'
import { Route as authLoginLayoutRouteImport } from './../../pages/(auth)/login/layout'
import { Route as adminMultiMenuLayoutRouteImport } from './../../pages/(admin)/multi-menu/layout'
import { Route as adminManageLayoutRouteImport } from './../../pages/(admin)/manage/layout'
import { Route as adminExceptionLayoutRouteImport } from './../../pages/(admin)/exception/layout'
import { Route as authLoginIndexRouteImport } from './../../pages/(auth)/login/index'
import { Route as adminMultiMenuIndexRouteImport } from './../../pages/(admin)/multi-menu/index'
import { Route as adminManageIndexRouteImport } from './../../pages/(admin)/manage/index'
import { Route as adminHomeIndexRouteImport } from './../../pages/(admin)/home/index'
import { Route as adminExceptionIndexRouteImport } from './../../pages/(admin)/exception/index'
import { Route as adminAboutIndexRouteImport } from './../../pages/(admin)/about/index'
import { Route as authLoginResetPwdRouteImport } from './../../pages/(auth)/login/reset-pwd'
import { Route as authLoginRegisterRouteImport } from './../../pages/(auth)/login/register'
import { Route as authLoginCodeLoginRouteImport } from './../../pages/(auth)/login/code-login'
import { Route as adminException500RouteImport } from './../../pages/(admin)/exception/500'
import { Route as adminException404RouteImport } from './../../pages/(admin)/exception/404'
import { Route as adminException403RouteImport } from './../../pages/(admin)/exception/403'
import { Route as adminMultiMenuSecondLayoutRouteImport } from './../../pages/(admin)/multi-menu/second/layout'
import { Route as adminMultiMenuFirstLayoutRouteImport } from './../../pages/(admin)/multi-menu/first/layout'
import { Route as adminMultiMenuSecondIndexRouteImport } from './../../pages/(admin)/multi-menu/second/index'
import { Route as adminMultiMenuFirstIndexRouteImport } from './../../pages/(admin)/multi-menu/first/index'
import { Route as adminManageUserIndexRouteImport } from './../../pages/(admin)/manage/user/index'
import { Route as adminManageRoleIndexRouteImport } from './../../pages/(admin)/manage/role/index'
import { Route as adminManageMenuIndexRouteImport } from './../../pages/(admin)/manage/menu/index'
import { Route as adminMultiMenuFirstChildRouteImport } from './../../pages/(admin)/multi-menu/first/child'
import { Route as adminManageUserIdRouteImport } from './../../pages/(admin)/manage/user/$id'
import { Route as adminBuiltinIframePageUrlRouteImport } from './../../pages/(admin)/_builtin/iframe-page/$url'
import { Route as adminMultiMenuSecondChildLayoutRouteImport } from './../../pages/(admin)/multi-menu/second/child/layout'
import { Route as adminMultiMenuSecondChildIndexRouteImport } from './../../pages/(admin)/multi-menu/second/child/index'
import { Route as adminMultiMenuSecondChildHomeRouteImport } from './../../pages/(admin)/multi-menu/second/child/home'

const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginOutRoute = authLoginOutRouteImport.update({
  id: '/(auth)/login-out',
  path: '/login-out',
  getParentRoute: () => rootRouteImport,
} as any)
const adminUserCenterRoute = adminUserCenterRouteImport.update({
  id: '/user-center',
  path: '/user-center',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminSoybeanDocsIframeRoute = adminSoybeanDocsIframeRouteImport.update({
  id: '/soybean-docs-iframe',
  path: '/soybean-docs-iframe',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminSoybeanDocsRoute = adminSoybeanDocsRouteImport.update({
  id: '/soybean-docs',
  path: '/soybean-docs',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminKeepAliveFormRoute = adminKeepAliveFormRouteImport.update({
  id: '/keep-alive-form',
  path: '/keep-alive-form',
  getParentRoute: () => adminLayoutRoute,
} as any)
const authLoginLayoutRoute = authLoginLayoutRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const adminMultiMenuLayoutRoute = adminMultiMenuLayoutRouteImport.update({
  id: '/multi-menu',
  path: '/multi-menu',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminManageLayoutRoute = adminManageLayoutRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminExceptionLayoutRoute = adminExceptionLayoutRouteImport.update({
  id: '/exception',
  path: '/exception',
  getParentRoute: () => adminLayoutRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLoginLayoutRoute,
} as any)
const adminMultiMenuIndexRoute = adminMultiMenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminMultiMenuLayoutRoute,
} as any)
const adminManageIndexRoute = adminManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminManageLayoutRoute,
} as any)
const adminHomeIndexRoute = adminHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminExceptionIndexRoute = adminExceptionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminExceptionLayoutRoute,
} as any)
const adminAboutIndexRoute = adminAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const authLoginResetPwdRoute = authLoginResetPwdRouteImport.update({
  id: '/reset-pwd',
  path: '/reset-pwd',
  getParentRoute: () => authLoginLayoutRoute,
} as any)
const authLoginRegisterRoute = authLoginRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authLoginLayoutRoute,
} as any)
const authLoginCodeLoginRoute = authLoginCodeLoginRouteImport.update({
  id: '/code-login',
  path: '/code-login',
  getParentRoute: () => authLoginLayoutRoute,
} as any)
const adminException500Route = adminException500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => adminExceptionLayoutRoute,
} as any)
const adminException404Route = adminException404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => adminExceptionLayoutRoute,
} as any)
const adminException403Route = adminException403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => adminExceptionLayoutRoute,
} as any)
const adminMultiMenuSecondLayoutRoute =
  adminMultiMenuSecondLayoutRouteImport.update({
    id: '/second',
    path: '/second',
    getParentRoute: () => adminMultiMenuLayoutRoute,
  } as any)
const adminMultiMenuFirstLayoutRoute =
  adminMultiMenuFirstLayoutRouteImport.update({
    id: '/first',
    path: '/first',
    getParentRoute: () => adminMultiMenuLayoutRoute,
  } as any)
const adminMultiMenuSecondIndexRoute =
  adminMultiMenuSecondIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminMultiMenuSecondLayoutRoute,
  } as any)
const adminMultiMenuFirstIndexRoute =
  adminMultiMenuFirstIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminMultiMenuFirstLayoutRoute,
  } as any)
const adminManageUserIndexRoute = adminManageUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => adminManageLayoutRoute,
} as any)
const adminManageRoleIndexRoute = adminManageRoleIndexRouteImport.update({
  id: '/role/',
  path: '/role/',
  getParentRoute: () => adminManageLayoutRoute,
} as any)
const adminManageMenuIndexRoute = adminManageMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => adminManageLayoutRoute,
} as any)
const adminMultiMenuFirstChildRoute =
  adminMultiMenuFirstChildRouteImport.update({
    id: '/child',
    path: '/child',
    getParentRoute: () => adminMultiMenuFirstLayoutRoute,
  } as any)
const adminManageUserIdRoute = adminManageUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => adminManageLayoutRoute,
} as any)
const adminBuiltinIframePageUrlRoute =
  adminBuiltinIframePageUrlRouteImport.update({
    id: '/_builtin/iframe-page/$url',
    path: '/iframe-page/$url',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminMultiMenuSecondChildLayoutRoute =
  adminMultiMenuSecondChildLayoutRouteImport.update({
    id: '/child',
    path: '/child',
    getParentRoute: () => adminMultiMenuSecondLayoutRoute,
  } as any)
const adminMultiMenuSecondChildIndexRoute =
  adminMultiMenuSecondChildIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminMultiMenuSecondChildLayoutRoute,
  } as any)
const adminMultiMenuSecondChildHomeRoute =
  adminMultiMenuSecondChildHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => adminMultiMenuSecondChildLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exception': typeof adminExceptionLayoutRouteWithChildren
  '/manage': typeof adminManageLayoutRouteWithChildren
  '/multi-menu': typeof adminMultiMenuLayoutRouteWithChildren
  '/login': typeof authLoginLayoutRouteWithChildren
  '/keep-alive-form': typeof adminKeepAliveFormRoute
  '/soybean-docs': typeof adminSoybeanDocsRoute
  '/soybean-docs-iframe': typeof adminSoybeanDocsIframeRoute
  '/user-center': typeof adminUserCenterRoute
  '/login-out': typeof authLoginOutRoute
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/multi-menu/first': typeof adminMultiMenuFirstLayoutRouteWithChildren
  '/multi-menu/second': typeof adminMultiMenuSecondLayoutRouteWithChildren
  '/exception/403': typeof adminException403Route
  '/exception/404': typeof adminException404Route
  '/exception/500': typeof adminException500Route
  '/login/code-login': typeof authLoginCodeLoginRoute
  '/login/register': typeof authLoginRegisterRoute
  '/login/reset-pwd': typeof authLoginResetPwdRoute
  '/about/': typeof adminAboutIndexRoute
  '/exception/': typeof adminExceptionIndexRoute
  '/home/': typeof adminHomeIndexRoute
  '/manage/': typeof adminManageIndexRoute
  '/multi-menu/': typeof adminMultiMenuIndexRoute
  '/login/': typeof authLoginIndexRoute
  '/multi-menu/second/child': typeof adminMultiMenuSecondChildLayoutRouteWithChildren
  '/iframe-page/$url': typeof adminBuiltinIframePageUrlRoute
  '/manage/user/$id': typeof adminManageUserIdRoute
  '/multi-menu/first/child': typeof adminMultiMenuFirstChildRoute
  '/manage/menu/': typeof adminManageMenuIndexRoute
  '/manage/role/': typeof adminManageRoleIndexRoute
  '/manage/user/': typeof adminManageUserIndexRoute
  '/multi-menu/first/': typeof adminMultiMenuFirstIndexRoute
  '/multi-menu/second/': typeof adminMultiMenuSecondIndexRoute
  '/multi-menu/second/child/home': typeof adminMultiMenuSecondChildHomeRoute
  '/multi-menu/second/child/': typeof adminMultiMenuSecondChildIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/keep-alive-form': typeof adminKeepAliveFormRoute
  '/soybean-docs': typeof adminSoybeanDocsRoute
  '/soybean-docs-iframe': typeof adminSoybeanDocsIframeRoute
  '/user-center': typeof adminUserCenterRoute
  '/login-out': typeof authLoginOutRoute
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/exception/403': typeof adminException403Route
  '/exception/404': typeof adminException404Route
  '/exception/500': typeof adminException500Route
  '/login/code-login': typeof authLoginCodeLoginRoute
  '/login/register': typeof authLoginRegisterRoute
  '/login/reset-pwd': typeof authLoginResetPwdRoute
  '/about': typeof adminAboutIndexRoute
  '/exception': typeof adminExceptionIndexRoute
  '/home': typeof adminHomeIndexRoute
  '/manage': typeof adminManageIndexRoute
  '/multi-menu': typeof adminMultiMenuIndexRoute
  '/login': typeof authLoginIndexRoute
  '/iframe-page/$url': typeof adminBuiltinIframePageUrlRoute
  '/manage/user/$id': typeof adminManageUserIdRoute
  '/multi-menu/first/child': typeof adminMultiMenuFirstChildRoute
  '/manage/menu': typeof adminManageMenuIndexRoute
  '/manage/role': typeof adminManageRoleIndexRoute
  '/manage/user': typeof adminManageUserIndexRoute
  '/multi-menu/first': typeof adminMultiMenuFirstIndexRoute
  '/multi-menu/second': typeof adminMultiMenuSecondIndexRoute
  '/multi-menu/second/child/home': typeof adminMultiMenuSecondChildHomeRoute
  '/multi-menu/second/child': typeof adminMultiMenuSecondChildIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)': typeof adminLayoutRouteWithChildren
  '/(admin)/exception': typeof adminExceptionLayoutRouteWithChildren
  '/(admin)/manage': typeof adminManageLayoutRouteWithChildren
  '/(admin)/multi-menu': typeof adminMultiMenuLayoutRouteWithChildren
  '/(auth)/login': typeof authLoginLayoutRouteWithChildren
  '/(admin)/keep-alive-form': typeof adminKeepAliveFormRoute
  '/(admin)/soybean-docs': typeof adminSoybeanDocsRoute
  '/(admin)/soybean-docs-iframe': typeof adminSoybeanDocsIframeRoute
  '/(admin)/user-center': typeof adminUserCenterRoute
  '/(auth)/login-out': typeof authLoginOutRoute
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(admin)/multi-menu/first': typeof adminMultiMenuFirstLayoutRouteWithChildren
  '/(admin)/multi-menu/second': typeof adminMultiMenuSecondLayoutRouteWithChildren
  '/(admin)/exception/403': typeof adminException403Route
  '/(admin)/exception/404': typeof adminException404Route
  '/(admin)/exception/500': typeof adminException500Route
  '/(auth)/login/code-login': typeof authLoginCodeLoginRoute
  '/(auth)/login/register': typeof authLoginRegisterRoute
  '/(auth)/login/reset-pwd': typeof authLoginResetPwdRoute
  '/(admin)/about/': typeof adminAboutIndexRoute
  '/(admin)/exception/': typeof adminExceptionIndexRoute
  '/(admin)/home/': typeof adminHomeIndexRoute
  '/(admin)/manage/': typeof adminManageIndexRoute
  '/(admin)/multi-menu/': typeof adminMultiMenuIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(admin)/multi-menu/second/child': typeof adminMultiMenuSecondChildLayoutRouteWithChildren
  '/(admin)/_builtin/iframe-page/$url': typeof adminBuiltinIframePageUrlRoute
  '/(admin)/manage/user/$id': typeof adminManageUserIdRoute
  '/(admin)/multi-menu/first/child': typeof adminMultiMenuFirstChildRoute
  '/(admin)/manage/menu/': typeof adminManageMenuIndexRoute
  '/(admin)/manage/role/': typeof adminManageRoleIndexRoute
  '/(admin)/manage/user/': typeof adminManageUserIndexRoute
  '/(admin)/multi-menu/first/': typeof adminMultiMenuFirstIndexRoute
  '/(admin)/multi-menu/second/': typeof adminMultiMenuSecondIndexRoute
  '/(admin)/multi-menu/second/child/home': typeof adminMultiMenuSecondChildHomeRoute
  '/(admin)/multi-menu/second/child/': typeof adminMultiMenuSecondChildIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exception'
    | '/manage'
    | '/multi-menu'
    | '/login'
    | '/keep-alive-form'
    | '/soybean-docs'
    | '/soybean-docs-iframe'
    | '/user-center'
    | '/login-out'
    | '/403'
    | '/404'
    | '/500'
    | '/multi-menu/first'
    | '/multi-menu/second'
    | '/exception/403'
    | '/exception/404'
    | '/exception/500'
    | '/login/code-login'
    | '/login/register'
    | '/login/reset-pwd'
    | '/about/'
    | '/exception/'
    | '/home/'
    | '/manage/'
    | '/multi-menu/'
    | '/login/'
    | '/multi-menu/second/child'
    | '/iframe-page/$url'
    | '/manage/user/$id'
    | '/multi-menu/first/child'
    | '/manage/menu/'
    | '/manage/role/'
    | '/manage/user/'
    | '/multi-menu/first/'
    | '/multi-menu/second/'
    | '/multi-menu/second/child/home'
    | '/multi-menu/second/child/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/keep-alive-form'
    | '/soybean-docs'
    | '/soybean-docs-iframe'
    | '/user-center'
    | '/login-out'
    | '/403'
    | '/404'
    | '/500'
    | '/exception/403'
    | '/exception/404'
    | '/exception/500'
    | '/login/code-login'
    | '/login/register'
    | '/login/reset-pwd'
    | '/about'
    | '/exception'
    | '/home'
    | '/manage'
    | '/multi-menu'
    | '/login'
    | '/iframe-page/$url'
    | '/manage/user/$id'
    | '/multi-menu/first/child'
    | '/manage/menu'
    | '/manage/role'
    | '/manage/user'
    | '/multi-menu/first'
    | '/multi-menu/second'
    | '/multi-menu/second/child/home'
    | '/multi-menu/second/child'
  id:
    | '__root__'
    | '/'
    | '/(admin)'
    | '/(admin)/exception'
    | '/(admin)/manage'
    | '/(admin)/multi-menu'
    | '/(auth)/login'
    | '/(admin)/keep-alive-form'
    | '/(admin)/soybean-docs'
    | '/(admin)/soybean-docs-iframe'
    | '/(admin)/user-center'
    | '/(auth)/login-out'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(admin)/multi-menu/first'
    | '/(admin)/multi-menu/second'
    | '/(admin)/exception/403'
    | '/(admin)/exception/404'
    | '/(admin)/exception/500'
    | '/(auth)/login/code-login'
    | '/(auth)/login/register'
    | '/(auth)/login/reset-pwd'
    | '/(admin)/about/'
    | '/(admin)/exception/'
    | '/(admin)/home/'
    | '/(admin)/manage/'
    | '/(admin)/multi-menu/'
    | '/(auth)/login/'
    | '/(admin)/multi-menu/second/child'
    | '/(admin)/_builtin/iframe-page/$url'
    | '/(admin)/manage/user/$id'
    | '/(admin)/multi-menu/first/child'
    | '/(admin)/manage/menu/'
    | '/(admin)/manage/role/'
    | '/(admin)/manage/user/'
    | '/(admin)/multi-menu/first/'
    | '/(admin)/multi-menu/second/'
    | '/(admin)/multi-menu/second/child/home'
    | '/(admin)/multi-menu/second/child/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  authLoginLayoutRoute: typeof authLoginLayoutRouteWithChildren
  authLoginOutRoute: typeof authLoginOutRoute
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login-out': {
      id: '/(auth)/login-out'
      path: '/login-out'
      fullPath: '/login-out'
      preLoaderRoute: typeof authLoginOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/user-center': {
      id: '/(admin)/user-center'
      path: '/user-center'
      fullPath: '/user-center'
      preLoaderRoute: typeof adminUserCenterRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/soybean-docs-iframe': {
      id: '/(admin)/soybean-docs-iframe'
      path: '/soybean-docs-iframe'
      fullPath: '/soybean-docs-iframe'
      preLoaderRoute: typeof adminSoybeanDocsIframeRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/soybean-docs': {
      id: '/(admin)/soybean-docs'
      path: '/soybean-docs'
      fullPath: '/soybean-docs'
      preLoaderRoute: typeof adminSoybeanDocsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/keep-alive-form': {
      id: '/(admin)/keep-alive-form'
      path: '/keep-alive-form'
      fullPath: '/keep-alive-form'
      preLoaderRoute: typeof adminKeepAliveFormRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/multi-menu': {
      id: '/(admin)/multi-menu'
      path: '/multi-menu'
      fullPath: '/multi-menu'
      preLoaderRoute: typeof adminMultiMenuLayoutRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/manage': {
      id: '/(admin)/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof adminManageLayoutRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/exception': {
      id: '/(admin)/exception'
      path: '/exception'
      fullPath: '/exception'
      preLoaderRoute: typeof adminExceptionLayoutRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authLoginLayoutRoute
    }
    '/(admin)/multi-menu/': {
      id: '/(admin)/multi-menu/'
      path: '/'
      fullPath: '/multi-menu/'
      preLoaderRoute: typeof adminMultiMenuIndexRouteImport
      parentRoute: typeof adminMultiMenuLayoutRoute
    }
    '/(admin)/manage/': {
      id: '/(admin)/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof adminManageIndexRouteImport
      parentRoute: typeof adminManageLayoutRoute
    }
    '/(admin)/home/': {
      id: '/(admin)/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof adminHomeIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/exception/': {
      id: '/(admin)/exception/'
      path: '/'
      fullPath: '/exception/'
      preLoaderRoute: typeof adminExceptionIndexRouteImport
      parentRoute: typeof adminExceptionLayoutRoute
    }
    '/(admin)/about/': {
      id: '/(admin)/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof adminAboutIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(auth)/login/reset-pwd': {
      id: '/(auth)/login/reset-pwd'
      path: '/reset-pwd'
      fullPath: '/login/reset-pwd'
      preLoaderRoute: typeof authLoginResetPwdRouteImport
      parentRoute: typeof authLoginLayoutRoute
    }
    '/(auth)/login/register': {
      id: '/(auth)/login/register'
      path: '/register'
      fullPath: '/login/register'
      preLoaderRoute: typeof authLoginRegisterRouteImport
      parentRoute: typeof authLoginLayoutRoute
    }
    '/(auth)/login/code-login': {
      id: '/(auth)/login/code-login'
      path: '/code-login'
      fullPath: '/login/code-login'
      preLoaderRoute: typeof authLoginCodeLoginRouteImport
      parentRoute: typeof authLoginLayoutRoute
    }
    '/(admin)/exception/500': {
      id: '/(admin)/exception/500'
      path: '/500'
      fullPath: '/exception/500'
      preLoaderRoute: typeof adminException500RouteImport
      parentRoute: typeof adminExceptionLayoutRoute
    }
    '/(admin)/exception/404': {
      id: '/(admin)/exception/404'
      path: '/404'
      fullPath: '/exception/404'
      preLoaderRoute: typeof adminException404RouteImport
      parentRoute: typeof adminExceptionLayoutRoute
    }
    '/(admin)/exception/403': {
      id: '/(admin)/exception/403'
      path: '/403'
      fullPath: '/exception/403'
      preLoaderRoute: typeof adminException403RouteImport
      parentRoute: typeof adminExceptionLayoutRoute
    }
    '/(admin)/multi-menu/second': {
      id: '/(admin)/multi-menu/second'
      path: '/second'
      fullPath: '/multi-menu/second'
      preLoaderRoute: typeof adminMultiMenuSecondLayoutRouteImport
      parentRoute: typeof adminMultiMenuLayoutRoute
    }
    '/(admin)/multi-menu/first': {
      id: '/(admin)/multi-menu/first'
      path: '/first'
      fullPath: '/multi-menu/first'
      preLoaderRoute: typeof adminMultiMenuFirstLayoutRouteImport
      parentRoute: typeof adminMultiMenuLayoutRoute
    }
    '/(admin)/multi-menu/second/': {
      id: '/(admin)/multi-menu/second/'
      path: '/'
      fullPath: '/multi-menu/second/'
      preLoaderRoute: typeof adminMultiMenuSecondIndexRouteImport
      parentRoute: typeof adminMultiMenuSecondLayoutRoute
    }
    '/(admin)/multi-menu/first/': {
      id: '/(admin)/multi-menu/first/'
      path: '/'
      fullPath: '/multi-menu/first/'
      preLoaderRoute: typeof adminMultiMenuFirstIndexRouteImport
      parentRoute: typeof adminMultiMenuFirstLayoutRoute
    }
    '/(admin)/manage/user/': {
      id: '/(admin)/manage/user/'
      path: '/user'
      fullPath: '/manage/user/'
      preLoaderRoute: typeof adminManageUserIndexRouteImport
      parentRoute: typeof adminManageLayoutRoute
    }
    '/(admin)/manage/role/': {
      id: '/(admin)/manage/role/'
      path: '/role'
      fullPath: '/manage/role/'
      preLoaderRoute: typeof adminManageRoleIndexRouteImport
      parentRoute: typeof adminManageLayoutRoute
    }
    '/(admin)/manage/menu/': {
      id: '/(admin)/manage/menu/'
      path: '/menu'
      fullPath: '/manage/menu/'
      preLoaderRoute: typeof adminManageMenuIndexRouteImport
      parentRoute: typeof adminManageLayoutRoute
    }
    '/(admin)/multi-menu/first/child': {
      id: '/(admin)/multi-menu/first/child'
      path: '/child'
      fullPath: '/multi-menu/first/child'
      preLoaderRoute: typeof adminMultiMenuFirstChildRouteImport
      parentRoute: typeof adminMultiMenuFirstLayoutRoute
    }
    '/(admin)/manage/user/$id': {
      id: '/(admin)/manage/user/$id'
      path: '/user/$id'
      fullPath: '/manage/user/$id'
      preLoaderRoute: typeof adminManageUserIdRouteImport
      parentRoute: typeof adminManageLayoutRoute
    }
    '/(admin)/_builtin/iframe-page/$url': {
      id: '/(admin)/_builtin/iframe-page/$url'
      path: '/iframe-page/$url'
      fullPath: '/iframe-page/$url'
      preLoaderRoute: typeof adminBuiltinIframePageUrlRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/multi-menu/second/child': {
      id: '/(admin)/multi-menu/second/child'
      path: '/child'
      fullPath: '/multi-menu/second/child'
      preLoaderRoute: typeof adminMultiMenuSecondChildLayoutRouteImport
      parentRoute: typeof adminMultiMenuSecondLayoutRoute
    }
    '/(admin)/multi-menu/second/child/': {
      id: '/(admin)/multi-menu/second/child/'
      path: '/'
      fullPath: '/multi-menu/second/child/'
      preLoaderRoute: typeof adminMultiMenuSecondChildIndexRouteImport
      parentRoute: typeof adminMultiMenuSecondChildLayoutRoute
    }
    '/(admin)/multi-menu/second/child/home': {
      id: '/(admin)/multi-menu/second/child/home'
      path: '/home'
      fullPath: '/multi-menu/second/child/home'
      preLoaderRoute: typeof adminMultiMenuSecondChildHomeRouteImport
      parentRoute: typeof adminMultiMenuSecondChildLayoutRoute
    }
  }
}

interface adminExceptionLayoutRouteChildren {
  adminException403Route: typeof adminException403Route
  adminException404Route: typeof adminException404Route
  adminException500Route: typeof adminException500Route
  adminExceptionIndexRoute: typeof adminExceptionIndexRoute
}

const adminExceptionLayoutRouteChildren: adminExceptionLayoutRouteChildren = {
  adminException403Route: adminException403Route,
  adminException404Route: adminException404Route,
  adminException500Route: adminException500Route,
  adminExceptionIndexRoute: adminExceptionIndexRoute,
}

const adminExceptionLayoutRouteWithChildren =
  adminExceptionLayoutRoute._addFileChildren(adminExceptionLayoutRouteChildren)

interface adminManageLayoutRouteChildren {
  adminManageIndexRoute: typeof adminManageIndexRoute
  adminManageUserIdRoute: typeof adminManageUserIdRoute
  adminManageMenuIndexRoute: typeof adminManageMenuIndexRoute
  adminManageRoleIndexRoute: typeof adminManageRoleIndexRoute
  adminManageUserIndexRoute: typeof adminManageUserIndexRoute
}

const adminManageLayoutRouteChildren: adminManageLayoutRouteChildren = {
  adminManageIndexRoute: adminManageIndexRoute,
  adminManageUserIdRoute: adminManageUserIdRoute,
  adminManageMenuIndexRoute: adminManageMenuIndexRoute,
  adminManageRoleIndexRoute: adminManageRoleIndexRoute,
  adminManageUserIndexRoute: adminManageUserIndexRoute,
}

const adminManageLayoutRouteWithChildren =
  adminManageLayoutRoute._addFileChildren(adminManageLayoutRouteChildren)

interface adminMultiMenuFirstLayoutRouteChildren {
  adminMultiMenuFirstChildRoute: typeof adminMultiMenuFirstChildRoute
  adminMultiMenuFirstIndexRoute: typeof adminMultiMenuFirstIndexRoute
}

const adminMultiMenuFirstLayoutRouteChildren: adminMultiMenuFirstLayoutRouteChildren =
  {
    adminMultiMenuFirstChildRoute: adminMultiMenuFirstChildRoute,
    adminMultiMenuFirstIndexRoute: adminMultiMenuFirstIndexRoute,
  }

const adminMultiMenuFirstLayoutRouteWithChildren =
  adminMultiMenuFirstLayoutRoute._addFileChildren(
    adminMultiMenuFirstLayoutRouteChildren,
  )

interface adminMultiMenuSecondChildLayoutRouteChildren {
  adminMultiMenuSecondChildHomeRoute: typeof adminMultiMenuSecondChildHomeRoute
  adminMultiMenuSecondChildIndexRoute: typeof adminMultiMenuSecondChildIndexRoute
}

const adminMultiMenuSecondChildLayoutRouteChildren: adminMultiMenuSecondChildLayoutRouteChildren =
  {
    adminMultiMenuSecondChildHomeRoute: adminMultiMenuSecondChildHomeRoute,
    adminMultiMenuSecondChildIndexRoute: adminMultiMenuSecondChildIndexRoute,
  }

const adminMultiMenuSecondChildLayoutRouteWithChildren =
  adminMultiMenuSecondChildLayoutRoute._addFileChildren(
    adminMultiMenuSecondChildLayoutRouteChildren,
  )

interface adminMultiMenuSecondLayoutRouteChildren {
  adminMultiMenuSecondChildLayoutRoute: typeof adminMultiMenuSecondChildLayoutRouteWithChildren
  adminMultiMenuSecondIndexRoute: typeof adminMultiMenuSecondIndexRoute
}

const adminMultiMenuSecondLayoutRouteChildren: adminMultiMenuSecondLayoutRouteChildren =
  {
    adminMultiMenuSecondChildLayoutRoute:
      adminMultiMenuSecondChildLayoutRouteWithChildren,
    adminMultiMenuSecondIndexRoute: adminMultiMenuSecondIndexRoute,
  }

const adminMultiMenuSecondLayoutRouteWithChildren =
  adminMultiMenuSecondLayoutRoute._addFileChildren(
    adminMultiMenuSecondLayoutRouteChildren,
  )

interface adminMultiMenuLayoutRouteChildren {
  adminMultiMenuFirstLayoutRoute: typeof adminMultiMenuFirstLayoutRouteWithChildren
  adminMultiMenuSecondLayoutRoute: typeof adminMultiMenuSecondLayoutRouteWithChildren
  adminMultiMenuIndexRoute: typeof adminMultiMenuIndexRoute
}

const adminMultiMenuLayoutRouteChildren: adminMultiMenuLayoutRouteChildren = {
  adminMultiMenuFirstLayoutRoute: adminMultiMenuFirstLayoutRouteWithChildren,
  adminMultiMenuSecondLayoutRoute: adminMultiMenuSecondLayoutRouteWithChildren,
  adminMultiMenuIndexRoute: adminMultiMenuIndexRoute,
}

const adminMultiMenuLayoutRouteWithChildren =
  adminMultiMenuLayoutRoute._addFileChildren(adminMultiMenuLayoutRouteChildren)

interface adminLayoutRouteChildren {
  adminExceptionLayoutRoute: typeof adminExceptionLayoutRouteWithChildren
  adminManageLayoutRoute: typeof adminManageLayoutRouteWithChildren
  adminMultiMenuLayoutRoute: typeof adminMultiMenuLayoutRouteWithChildren
  adminKeepAliveFormRoute: typeof adminKeepAliveFormRoute
  adminSoybeanDocsRoute: typeof adminSoybeanDocsRoute
  adminSoybeanDocsIframeRoute: typeof adminSoybeanDocsIframeRoute
  adminUserCenterRoute: typeof adminUserCenterRoute
  adminAboutIndexRoute: typeof adminAboutIndexRoute
  adminHomeIndexRoute: typeof adminHomeIndexRoute
  adminBuiltinIframePageUrlRoute: typeof adminBuiltinIframePageUrlRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminExceptionLayoutRoute: adminExceptionLayoutRouteWithChildren,
  adminManageLayoutRoute: adminManageLayoutRouteWithChildren,
  adminMultiMenuLayoutRoute: adminMultiMenuLayoutRouteWithChildren,
  adminKeepAliveFormRoute: adminKeepAliveFormRoute,
  adminSoybeanDocsRoute: adminSoybeanDocsRoute,
  adminSoybeanDocsIframeRoute: adminSoybeanDocsIframeRoute,
  adminUserCenterRoute: adminUserCenterRoute,
  adminAboutIndexRoute: adminAboutIndexRoute,
  adminHomeIndexRoute: adminHomeIndexRoute,
  adminBuiltinIframePageUrlRoute: adminBuiltinIframePageUrlRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

interface authLoginLayoutRouteChildren {
  authLoginCodeLoginRoute: typeof authLoginCodeLoginRoute
  authLoginRegisterRoute: typeof authLoginRegisterRoute
  authLoginResetPwdRoute: typeof authLoginResetPwdRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
}

const authLoginLayoutRouteChildren: authLoginLayoutRouteChildren = {
  authLoginCodeLoginRoute: authLoginCodeLoginRoute,
  authLoginRegisterRoute: authLoginRegisterRoute,
  authLoginResetPwdRoute: authLoginResetPwdRoute,
  authLoginIndexRoute: authLoginIndexRoute,
}

const authLoginLayoutRouteWithChildren = authLoginLayoutRoute._addFileChildren(
  authLoginLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminLayoutRoute: adminLayoutRouteWithChildren,
  authLoginLayoutRoute: authLoginLayoutRouteWithChildren,
  authLoginOutRoute: authLoginOutRoute,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
