import type { AnyRoute } from '@tanstack/react-router';

import type { AdminLayoutsDynamicRoutes } from '../../setup';
import { normalizePath } from './menu-generator';

export interface CreateAdminDynamicRouteLoaderOptions {
  /** Load raw backend routes from the consuming app. */
  loadBackendRoutes: () => Promise<Api.Route.BackendRouteResponse>;
  /** TanStack Router route tree generated by the consuming app. */
  routeTree: AnyRoute;
}

export interface NormalizeBackendRouteResponseOptions {
  /** TanStack Router route tree used to filter unavailable backend routes. */
  routeTree: AnyRoute;
}

export function collectAvailableRoutePaths(route: AnyRoute) {
  const paths = new Set<string>();

  function walk(currentRoute: AnyRoute) {
    const fullPath = normalizePath(currentRoute.fullPath ?? '');

    if (fullPath) {
      paths.add(fullPath);
    }

    const children = currentRoute.children as AnyRoute[] | undefined;
    children?.forEach(child => {
      walk(child);
    });
  }

  walk(route);

  return paths;
}

function toParentId(parentId?: number | string | null) {
  if (parentId === null || parentId === undefined) return null;

  return String(parentId);
}

function toRouteTab(handle: Api.Route.BackendRouteHandle) {
  return {
    fixedIndex: handle.fixedIndexInTab ,
    multi: handle.multiTab
  };
}

function isBackendRoute(route: Api.Route.BackendRoute | null): route is Api.Route.BackendRoute {
  return route !== null;
}

export function createBackendRouteNormalizer(routeTree: AnyRoute) {
  const availableRoutePaths = collectAvailableRoutePaths(routeTree);

  function normalizeBackendPath(path: string) {
    return normalizePath(path.replaceAll(/:([A-Za-z0-9_]+)/g, '$$$1'));
  }

  function toRoutePath(path: string) {
    return normalizeBackendPath(path) as Router.RoutePath;
  }

  function toAvailableRoutePath(path?: string | null) {
    if (!path) return null;

    const routePath = toRoutePath(path);

    return availableRoutePaths.has(routePath) ? routePath : null;
  }

  function toBackendRouteChildren(route: Api.Route.BackendRoutePayload) {
    const children = route.children?.map(toBackendRoute).filter(isBackendRoute) ?? [];

    return children.length ? children : [];
  }

  function toRouteMenu(handle: Api.Route.BackendRouteHandle) {
    return {
      activeMenu: toAvailableRoutePath(handle.activeMenu),
      badge: handle.badge ,
      extra: handle.extra ,
      hide: handle.hideInMenu ,
      icon: handle.icon ,
      localIcon: handle.localIcon ,
      order: handle.order ,
      type: handle.type
    };
  }

  function toBackendRoute(route: Api.Route.BackendRoutePayload): Api.Route.BackendRoute | null {
    const path = toRoutePath(route.path);

    if (!availableRoutePaths.has(path)) {
      return null;
    }

    const handle = route.handle ?? route.meta ?? {};

    return {
      id: String(route.id ?? route.name ?? path),
      children: toBackendRouteChildren(route),
      href: handle.href ,
      i18nKey: handle.i18nKey ,
      keepAlive: handle.keepAlive ,
      layout: route.layout ,
      menu: toRouteMenu(handle),
      parentId: toParentId(route.parentId),
      path,
      permissions: handle.roles ,
      tab: toRouteTab(handle),
      title: handle.title ?? route.name,
      url: handle.url
    };
  }

  return function normalizeRouteResponse(routeData: Api.Route.BackendRouteResponse): AdminLayoutsDynamicRoutes {
    return {
      home: toAvailableRoutePath(routeData.home),
      routes: routeData.routes.map(toBackendRoute).filter(isBackendRoute)
    };
  };
}

export function normalizeBackendRouteResponse(
  routeData: Api.Route.BackendRouteResponse,
  options: NormalizeBackendRouteResponseOptions
) {
  return createBackendRouteNormalizer(options.routeTree)(routeData);
}

export function createAdminDynamicRouteLoader(options: CreateAdminDynamicRouteLoaderOptions) {
  const { loadBackendRoutes, routeTree } = options;
  const normalizeBackendRoutes = createBackendRouteNormalizer(routeTree);

  return async function loadAdminDynamicRoutes() {
    const routeData = await loadBackendRoutes();

    return normalizeBackendRoutes(routeData);
  };
}
